Repository rudderlabs/rudder-sdk-android, pull requests merged in 2024-03, with the labels that each got.

#399 feat: move optOut out of configuration
  android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
  android/src/main/java/com/rudderstack/android/internal/RudderPreferenceManager.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/ReinstatePlugin.kt
  android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
  android/src/test/java/com/rudderstack/android/android/AndroidStorageTest.kt
  core/build.gradle
  core/src/main/java/com/rudderstack/core/Configuration.kt
  core/src/main/java/com/rudderstack/core/compat/ConfigurationBuilder.java
  core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
  core/src/main/java/com/rudderstack/core/internal/plugins/GDPRPlugin.kt
  core/src/test/java/com/rudderstack/core/compat/ConfigurationBuilderTest.java
  core/src/test/java/com/rudderstack/core/internal/plugins/EventSizeFilterPluginTest.kt
  core/src/test/java/com/rudderstack/core/internal/plugins/GDPRPluginTest.kt
Labels: Ready for review

#401 feat: replace instanceName field with the writeKey wherever applicable
  android/src/main/java/com/rudderstack/android/RudderAnalytics.kt
  android/src/main/java/com/rudderstack/android/compat/RudderAnalyticsBuilderCompat.java
  android/src/main/java/com/rudderstack/android/internal/RudderPreferenceManager.kt
  android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
  android/src/main/java/com/rudderstack/android/utilities/V1MigratoryUtils.kt
  android/src/test/java/com/rudderstack/android/android/AndroidStorageTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/ResetImplementationPluginTest.kt
  android/src/test/java/com/rudderstack/android/internal/plugins/ReinstatePluginTest.kt
  core/src/main/java/com/rudderstack/core/Analytics.kt
  core/src/main/java/com/rudderstack/core/Controller.kt
  core/src/main/java/com/rudderstack/core/compat/AnalyticsBuilderCompat.java
  core/src/main/java/com/rudderstack/core/flushpolicy/IntervalBasedFlushPolicy.kt
  core/src/main/java/com/rudderstack/core/holder/AnalyticsHolder.kt
  core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
  core/src/test/java/com/rudderstack/core/holder/AnalyticsHolderTest.kt
  core/src/test/java/com/rudderstack/core/holder/StatesHolderTest.kt
  rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/DefaultRudderReporter.kt
  rudderreporter/src/main/java/com/rudderstack/android/ruddermetricsreporterandroid/internal/DefaultReservoir.kt
Labels: Ready for review

#407 feat: add support for global customContext option
  core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
  core/src/test/java/com/rudderstack/android/sdk/core/EventRepositoryTest.java
Labels: Ready for review

#406 feat: added persistence support for advertisingId and api to clear advertisingId
  core/src/main/java/com/rudderstack/android/sdk/core/RudderClient.java
  core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java
  core/src/main/java/com/rudderstack/android/sdk/core/RudderDeviceInfo.java
  core/src/main/java/com/rudderstack/android/sdk/core/RudderElementCache.java
  core/src/main/java/com/rudderstack/android/sdk/core/RudderPreferenceManager.java
  sample-kotlin/build.gradle
Labels: Ready for review, v1

#409 fix: Application Opened event not being fired
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt
Labels: Ready for review, v2
