Repository rudderlabs/rudder-sdk-android, pull requests merged in 2024-06, with the labels that each got.

#443 fix: activity is now broadcasted irrespective of recordScreenView or trackLifecycle
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt
Labels: Ready for review, v2

#441 fix: delete v1 files server config and flush server config
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
  android/src/main/java/com/rudderstack/android/storage/AndroidStorage.kt
  android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
  android/src/main/java/com/rudderstack/android/storage/FileUtils.kt
Labels: Ready for review, v2

#440 fix: fixed adTrackingEnabled and wifi json value
  android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/PlatformInputsPlugin.kt
  android/src/main/java/com/rudderstack/android/utilities/AnalyticsUtil.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
Labels: v2

#438 fix: add sentAt field to each event
  core/src/main/java/com/rudderstack/core/internal/DataUploadServiceImpl.kt
  models/src/main/java/com/rudderstack/models/Message.kt
Labels: Ready for review, v2

#442 feat: sdk 1954 misc issues remove external ids and collect ad
  android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/FillDefaultsPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/PlatformInputsPlugin.kt
  android/src/test/java/com/rudderstack/android/plugins/ExtractStatePluginTest.kt
  android/src/test/java/com/rudderstack/android/plugins/FillDefaultsPluginTest.kt
  core/src/main/java/com/rudderstack/core/Analytics.kt
  core/src/main/java/com/rudderstack/core/Configuration.kt
  core/src/main/java/com/rudderstack/core/Controller.kt
  core/src/main/java/com/rudderstack/core/Dsl.kt
  core/src/main/java/com/rudderstack/core/RudderOption.kt
  core/src/main/java/com/rudderstack/core/compat/ConfigurationBuilder.java
  core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
  core/src/main/java/com/rudderstack/core/internal/plugins/RudderOptionPlugin.kt
  core/src/test/java/com/rudderstack/core/AnalyticsTest.kt
  core/src/test/java/com/rudderstack/core/compat/ConfigurationBuilderTest.java
  core/src/test/java/com/rudderstack/core/internal/plugins/RudderOptionPluginTest.kt
  models/src/main/java/com/rudderstack/models/Extensions.kt
  models/src/main/java/com/rudderstack/models/Utils.kt
  models/src/test/java/com/rudderstack/models/MessageUtilsTest.kt
  samples/sample-kotlin-android/build.gradle.kts
  samples/sample-kotlin-android/src/main/AndroidManifest.xml
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/mainview/MainViewModel.kt
Labels: v2

#434 feat: convert groovy build.gradle files to build.gradle.kts
  android/build.gradle
  android/build.gradle.kts
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/RudderstackBuildConfig.kt
  core/build.gradle
  core/build.gradle.kts
  gradle/libs.versions.toml
  gsonrudderadapter/build.gradle
  gsonrudderadapter/build.gradle.kts
  jacksonrudderadapter/build.gradle
  jacksonrudderadapter/build.gradle.kts
  libs/navigationplugin/build.gradle.kts
  libs/test-common/build.gradle.kts
  models/build.gradle
  models/build.gradle.kts
  moshirudderadapter/build.gradle
  moshirudderadapter/build.gradle.kts
  repository/build.gradle
  repository/build.gradle.kts
  rudderjsonadapter/build.gradle
  rudderjsonadapter/build.gradle.kts
  rudderreporter/build.gradle
  rudderreporter/build.gradle.kts
  samples/sample-kotlin-android/build.gradle.kts
  settings.gradle
  settings.gradle.kts
  web/build.gradle
  web/build.gradle.kts
Labels: v2

#437 feat: sdk 1800 migration code refactor
  android/src/main/java/com/rudderstack/android/AndroidUtils.kt
  android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
  android/src/main/java/com/rudderstack/android/compat/ConfigurationAndroidBuilder.java
  android/src/main/java/com/rudderstack/android/internal/RudderPreferenceManager.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/AnonymousIdHeaderPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/AppInstallUpdateTrackerPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/PlatformInputsPlugin.kt
  android/src/main/java/com/rudderstack/android/storage/AndroidStorage.kt
  android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
  android/src/main/java/com/rudderstack/android/storage/FileUtils.kt
  android/src/main/java/com/rudderstack/android/storage/MigrateV1ToV2Utils.kt
  android/src/main/java/com/rudderstack/android/utilities/AnalyticsUtil.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPluginTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/ReinstatePluginTest.kt
  core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
  models/src/main/java/com/rudderstack/models/Message.kt
  repository/src/main/java/com/rudderstack/android/repository/RudderDatabase.kt
Labels: v2

#444 feat: replace custom logger with logLevel
  android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
  android/src/main/java/com/rudderstack/android/compat/ConfigurationAndroidBuilder.java
  android/src/main/java/com/rudderstack/android/internal/AndroidLogger.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/AppInstallUpdateTrackerPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/FillDefaultsPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/PlatformInputsPlugin.kt
  android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
  android/src/main/java/com/rudderstack/android/storage/FileUtils.kt
  android/src/main/java/com/rudderstack/android/storage/MigrateV1ToV2Utils.kt
  android/src/main/java/com/rudderstack/android/utilities/SessionUtils.kt
  android/src/test/java/com/rudderstack/android/AndroidStorageTest.kt
  android/src/test/java/com/rudderstack/android/RudderAnalyticsTest.kt
  android/src/test/java/com/rudderstack/android/compat/ConfigurationAndroidBuilderTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/AppInstallUpdateTrackerPluginTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPluginTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/ReinstatePluginTest.kt
  android/src/test/java/com/rudderstack/android/plugins/ExtractStatePluginTest.kt
  android/src/test/java/com/rudderstack/android/plugins/FillDefaultsPluginTest.kt
  android/src/test/java/com/rudderstack/android/plugins/PlatformInputsPluginTest.kt
  android/src/test/java/com/rudderstack/android/utilities/AnalyticsUtilTest.kt
  android/src/test/java/com/rudderstack/android/utilities/SessionUtilsTest.kt
  android/src/test/java/com/rudderstack/android/utilities/V1MigratoryUtilsKtTest.kt
  core/src/main/java/com/rudderstack/core/BasicStorageImpl.kt
  core/src/main/java/com/rudderstack/core/Configuration.kt
  core/src/main/java/com/rudderstack/core/Controller.kt
  core/src/main/java/com/rudderstack/core/RetryStrategy.kt
  core/src/main/java/com/rudderstack/core/RudderLogger.kt
  core/src/main/java/com/rudderstack/core/compat/ConfigurationBuilder.java
  core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
  core/src/main/java/com/rudderstack/core/internal/KotlinLogger.kt
  core/src/main/java/com/rudderstack/core/internal/plugins/EventSizeFilterPlugin.kt
  core/src/test/java/com/rudderstack/core/compat/ConfigurationBuilderTest.java
  libs/sync/src/main/java/com/rudderstack/android/sync/WorkerManagerPlugin.kt
  libs/sync/src/main/java/com/rudderstack/android/sync/internal/DataSyncWorkManagerExtensions.kt
  libs/sync/src/main/java/com/rudderstack/android/sync/internal/RudderSyncWorker.kt
  libs/sync/src/test/java/com/rudderstack/android/sync/RudderSyncWorkerTest.kt
  libs/sync/src/test/java/com/rudderstack/android/sync/utils/TestLogger.kt
  libs/test-common/src/main/java/com/vagabond/testcommon/TestAnalyticsProvider.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
Labels: Ready for review, v2

#449 fix: database crash issue
  core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
  core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
  core/src/test/java/com/rudderstack/android/sdk/core/DBPersistentManagerTest.java
  settings.gradle
Labels: Ready for review, v1

#451 chore: update assignees, reviewer and codeowner
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/draft_new_release-v2.yml
  .github/workflows/draft_new_release.yml
  .github/workflows/publish-new-github-release-v2.yml
  .github/workflows/publish-new-github-release.yml
  CODEOWNERS
Labels: Ready for review

#452 chore(release): pulling release/1.23.2 into master
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/draft_new_release-v2.yml
  .github/workflows/draft_new_release.yml
  .github/workflows/publish-new-github-release-v2.yml
  .github/workflows/publish-new-github-release.yml
  CHANGELOG.md
  CODEOWNERS
  CONTRIBUTING.md
  README.md
  core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java
  core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java
  core/src/test/java/com/rudderstack/android/sdk/core/DBPersistentManagerTest.java
  gradle.properties
  package.json
  settings.gradle
Labels: v1

#448 fix: remove userId from the configurationAndroid class
  android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
  android/src/main/java/com/rudderstack/android/compat/ConfigurationAndroidBuilder.java
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/FillDefaultsPlugin.kt
  android/src/main/java/com/rudderstack/android/utilities/AnalyticsUtil.kt
  android/src/test/java/com/rudderstack/android/plugins/FillDefaultsPluginTest.kt
Labels: Ready for review, v2

#450 fix: screen event
  android/src/main/java/com/rudderstack/android/ConfigurationAndroid.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPlugin.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPluginTest.kt
  android/src/test/java/com/rudderstack/android/storage/MessageEntityTest.kt
  android/src/test/java/com/rudderstack/android/storage/MigrateV1ToV2UtilsTest.kt
  core/src/main/java/com/rudderstack/core/Dsl.kt
  models/src/main/java/com/rudderstack/models/Message.kt
Labels: Ready for review, v2

#446 fix: prevent setting duplicate externalId types
  android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
  core/src/main/java/com/rudderstack/core/RudderOption.kt
  core/src/test/java/com/rudderstack/core/RudderOptionTest.kt
  models/src/main/java/com/rudderstack/models/Extensions.kt
  models/src/test/java/com/rudderstack/models/MessageUtilsTest.kt
Labels: Ready for review, v2
