Repository rudderlabs/rudder-sdk-android, pull requests merged in 2024-05, with the labels that each got.

#421 feat: sdk 1351 refresh sourceconfig on set to foreground
  android/src/main/java/com/rudderstack/android/internal/RudderPreferenceManager.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPlugin.kt
  android/src/test/java/com/rudderstack/android/AndroidStorageTest.kt
  android/src/test/java/com/rudderstack/android/ExampleUnitTest.kt
  android/src/test/java/com/rudderstack/android/RudderAnalyticsTest.kt
  android/src/test/java/com/rudderstack/android/RudderSyncWorkerTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/AppInstallUpdateTrackerPluginTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPluginTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/ResetImplementationPluginTest.kt
  android/src/test/java/com/rudderstack/android/internal/plugins/ReinstatePluginTest.kt
  android/src/test/java/com/rudderstack/android/plugins/ExtractStatePluginTest.kt
  android/src/test/java/com/rudderstack/android/plugins/FillDefaultsPluginTest.kt
  android/src/test/java/com/rudderstack/android/plugins/PlatformInputsPluginTest.kt
  android/src/test/java/com/rudderstack/android/utils/TestExecutor.kt
  android/src/test/java/com/rudderstack/android/utils/TestLogger.kt
  android/src/test/java/com/rudderstack/android/utils/Utils.kt
  core/src/main/java/com/rudderstack/core/ConfigDownloadService.kt
  core/src/main/java/com/rudderstack/core/Controller.kt
  core/src/main/java/com/rudderstack/core/internal/AnalyticsDelegate.kt
  core/src/main/java/com/rudderstack/core/internal/ConfigDownloadServiceImpl.kt
  core/src/main/java/com/rudderstack/core/internal/plugins/CoreInputsPlugin.kt
  core/src/test/java/com/rudderstack/core/internal/ConfigDownloadServiceImplTest.kt
  core/src/test/java/com/rudderstack/core/internal/plugins/CoreInputsPluginTest.kt
  libs/test-common/src/main/java/com/vagabond/testcommon/AssertionPlugin.kt
  libs/test-common/src/main/java/com/vagabond/testcommon/MockConfigDownloadService.kt
  libs/test-common/src/main/java/com/vagabond/testcommon/TestAnalyticsProvider.kt
Labels: v2

#423 fix: key "batch" was being obfuscated due to proguard
  core/proguard-consumer-rules.pro
  core/src/main/java/com/rudderstack/android/sdk/core/TransformationRequest.java
  sample-kotlin/gradle.properties
  sample-kotlin/proguard-rules.pro
Labels: v1

#419 feat: migrate from sqlcipher legacy to latest version
  core/build.gradle
  core/src/main/java/com/rudderstack/android/sdk/core/persistence/DefaultPersistenceProvider.java
  core/src/main/java/com/rudderstack/android/sdk/core/persistence/EncryptedPersistence.java
  sample-kotlin/build.gradle
Labels: v1

#425 fix: deep linking crash
  core/src/main/java/com/rudderstack/android/sdk/core/util/Utils.java
Labels: Ready for review, v1

#424 feat: implement the analytics SDK as a singleton
  android/src/main/java/com/rudderstack/android/AnalyticsRegistry.kt
  android/src/main/java/com/rudderstack/android/RudderAnalytics.kt
  android/src/main/java/com/rudderstack/android/compat/RudderAnalyticsBuilderCompat.java
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ActivityBroadcasterPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/AnonymousIdHeaderPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/AppInstallUpdateTrackerPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/LifecycleObserverPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ReinstatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/infrastructure/ResetImplementationPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/ExtractStatePlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/FillDefaultsPlugin.kt
  android/src/main/java/com/rudderstack/android/internal/plugins/PlatformInputsPlugin.kt
  android/src/main/java/com/rudderstack/android/storage/RudderEntityFactory.kt
  android/src/main/java/com/rudderstack/android/utilities/AnalyticsUtil.kt
  android/src/main/java/com/rudderstack/android/utilities/SessionUtils.kt
  android/src/test/java/com/rudderstack/android/RudderAnalyticsTest.kt
  android/src/test/java/com/rudderstack/android/internal/infrastructure/ResetImplementationPluginTest.kt
  android/src/test/java/com/rudderstack/android/utilities/AnalyticsUtilTest.kt
  android/src/test/java/com/rudderstack/android/utilities/SessionUtilsTest.kt
  core/src/main/java/com/rudderstack/core/utilities/annotations.kt
  libs/navigationplugin/src/main/java/com/rudderstack/android/navigationplugin/Lifecycle.kt
  libs/navigationplugin/src/main/java/com/rudderstack/android/navigationplugin/internal/NavigationPlugin.kt
  libs/sync/src/main/java/com/rudderstack/android/sync/WorkerManagerPlugin.kt
  libs/sync/src/main/java/com/rudderstack/android/sync/internal/DataSyncWorkManagerExtensions.kt
  libs/sync/src/test/java/com/rudderstack/android/sync/RudderSyncWorkerTest.kt
  samples/sample-kotlin-android/build.gradle.kts
  samples/sample-kotlin-android/rudderstack.properties.sample
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/RudderAnalyticsUtils.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/Values.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/analytics/workmanger/SampleWorkManagerAnalyticsFactory.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/mainview/MainActivity.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/mainview/MainViewModel.kt
  samples/sample-kotlin-android/src/main/kotlin/com/rudderstack/android/sampleapp/mainview/MainViewModelState.kt
Labels: Ready for review, v2

#426 fix: serialization uid missing issue and repository all data as callback issue
  android/src/main/java/com/rudderstack/android/storage/AndroidStorageImpl.kt
  models/src/main/java/com/rudderstack/models/RudderServerConfig.kt
  models/src/test/java/com/rudderstack/models/JsonUtilities.kt
  models/src/test/java/com/rudderstack/models/RudderServerConfigParseTest.kt
  models/src/test/resources/mock/rudder_config_response.json
  models/src/test/resources/mock/rudder_config_response_2.json
  repository/src/main/java/com/rudderstack/android/repository/Dao.kt
Labels: v2
